var readlineSync = require('readline-sync');

const w = readlineSync.question('Hourly Wage:');
let mon = readlineSync.question('Monday:');
let tues = readlineSync.question('Tuesday:');
let wends = readlineSync.question('Wednesday:');
let thurs = readlineSync.question('Thursday:');
let fri = readlineSync.question('Friday:');
let sat= readlineSync.question("Satuday:");
let sun= readlineSync.question("Sunday: ");
let monday = Number(mon);
let tuesday = Number(tues);
let wendsday = Number(wends);
let thursday = Number(thurs);
let friday = Number(fri);
let saturday = Number(sat);
let sunday = Number(sun);
let wages = Number(w);
let hours = monday+tuesday+wendsday+thursday+friday+saturday+sunday;
let weeklypay = hours*wages;
console.log("You'll make $"+ weeklypay + " this week." );
